# Site settings
title: Viacheslav Korolev
tagline: Ruby on Rails Developer
email: korolvs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I’m a professional Ruby on Rails and AngularJS developer with love to clear code and server architecture.
  A big fan of tests, well-documented code and learning something new.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://korolvs.com" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
logourl: /assets/images/ruby.svg # Site logo
author: "Viacheslav Korolev"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#9f0213" #"#a80518" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: korolvs
    #twitter: gayanvirajith
    facebook: iamkorolev
    # gplus: +gayanvirajith
    # dribble: gayanvirajith
    #pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: korolvs

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 'UA-75324568-1'
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

gems: [jekyll-paginate]
